### ISSUE TITLE
the centroid of the i-th expert 是怎么计算的

### ISSUE THREAD

**Issue by qingyue2014** [ise-uiuc/xft#2]
你好，请问论文中计算router时， 提到的“the centroid of the i-th expert in the l-th MoE layer”是怎么计算的呢？

**Comment by natedingyifeng** [comment]
你好，这里我们沿用了DeepSeekMoE（ https://arxiv.org/abs/2401.06066 ）论文中的描述方式，在实际代码中这里的 $e_i^l$ 指代的是，第 $l$ 层的`gate_network`（ https://github.com/ise-uiuc/xft/blob/main/src/magicoder/model/modeling_llama_moe_upscaling_hf.py#L719 ）中对应expert $i$ 的部分。

**Comment by QingyuanLi1211** [comment]
感觉是一个mlp或更简单的线性层，不知道我理解的是否正确。

**Comment by natedingyifeng** [comment]
你的理解是正确的。这是MoE中gate network的常见设计，我们在这里是直接沿用了LLaMA-MoE（ https://github.com/pjlab-sys4nlp/llama-moe ）的实现方法（在论文中已说明）。
