### ISSUE TITLE
moe gate type

### ISSUE THREAD

**Issue by sharkdrop** [ise-uiuc/xft#3]
作者您好，我在尝试复现论文中的MoE-deepseek-coder-1.3b-base以及XFT-deepseek-coder-1.3b-base，我发现默认的moe_config与论文方法并不一致。

在提供的默认config中，gate type被设置为TopKBalancedNoisyGate
![image](https://github.com/user-attachments/assets/465b0dc5-4c80-4f48-9987-7cc97f1c0730)

但TopKBalancedNoisyGate并不会有shared mlp的存在
![image](https://github.com/user-attachments/assets/1f22abc8-e3e1-4d93-85d1-cf4d5630f692)

论文中使用的应该是modeling_llama_moe_upscaling_hf.py中的TopKUniversalBalancedNoisyGate或TopKUniversalBalancedNoNormalizationNoisyGate，请问要想复现论文中的MoE-deepseek-coder-1.3b-base以及XFT-deepseek-coder-1.3b-base，gate type应该设置为哪一个

**Comment by natedingyifeng** [comment]
你好，config文件提供的只是参数定义，我们具体使用的是`TopKUniversalBalancedNoisyGate`，请参考这个文件中的做法：https://github.com/ise-uiuc/xft/blob/main/src/magicoder/convert_dense_to_moe.py#L29
