### ISSUE TITLE
关于router和merge的问题

### ISSUE THREAD

**Issue by QingyuanLi1211** [ise-uiuc/xft#4]
您好作者，您们的工作非常有意义，有些问题想向您请教。
Q1. 关于路由的训练 & mixing coefficients的训练过程：在训练merge过程所使用的mixing coefficients时，如果不加干预，shared expert的权重会特别大，占绝对主导，那么merge的结果实际上就退化成了一个FFN，因此XFT采用了固定shared expert的merge权重为lambda，而剩余expert的merge权重通过训练的方式得到，是否可以这样理解？那么同样的，在训练expert的路由权重时（即第一次训练过程），是否会出现同样的情况？即shared expert在计算加权概率分布的时候，其权重会倾向于越来越大？在原论文中，shared expert的路由权重一直取1-stmax（Softmax中最大的那个概率）是不是就是出于缓解这个问题的目的？这样Softmax会倾向于不产生一个过为峰值的概率，这样shared expert的路由权重和其他normal expert的路由权重会趋于平均？
Q2.关于mixing coefficients的训练过程的代码实现：在xft/src/magicoder/convert_moe_to_weighted.py脚本中的第57行及其上下文，是初始化mixing coefficients的代码吗？即ds_coder_state_dict[key] = torch.tensor([1 for _ in range(num_experts-1)])。如果是，原论文中写到初始化的值好像是1-lambda/N-1，和这里直接初始化1有一点出入，请问是不是不影响最终的训练结果？另外，进行merge时，是直接将所有expert的权重、偏置的矩阵进行加权平均吗？代码实现是否对应xft/src/magicoder/convert_weighted_to_dense.py的第80行：ffn_weights_dense += experts_weighted_average[layer_name][expert_id] * experts_weight[layer_name][proj_name][expert_id]。
再次感谢您们所提供的颇有意义的工作。

**Comment by natedingyifeng** [comment]
你好，

> Q1. 关于路由的训练 & mixing coefficients的训练过程

对于第一点，你说的没错，”采用固定shared expert的merge权重为lambda“是为了不让shared expert的权重变得过大。

对于第二点，我们最初的出发点其实是，让所有expert的权重之和为1，以此来保证每一层moe layer的output的大小和upcycle之前dense model的FFN的output的大小基本一致，从而避免性能下降。不过你的想法也很有意思，值得探索👍。

> Q2.关于mixing coefficients的训练过程的代码实现

对于mixing coefficients的初始化，我们的实现和论文的描述是一致的。虽然在`convert_moe_to_weighted.py`文件中，normal expert的mixing coefficients被直接初始化为1，但是模型文件`modeling_llama_weighted_hf.py`的第706行代码（ https://github.com/ise-uiuc/xft/blob/main/src/magicoder/model/modeling_llama_weighted_hf.py#L706 ）会把这些coefficients转换成(1-lambda)/N-1。

对于merge的过程，你说的对，我们直接利用学到的mixing coefficients，将所有expert的权重矩阵进行加权平均。在我们使用的Llama架构里，FFN layer是没有偏置的（bias=False）。

**Comment by QingyuanLi1211** [comment]
感谢您的答复！
